#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

case "$1" in
  nvcc:nginx.conf)
    [[ -z $2 ]] && echo "Please specify an app to run the command on" && exit 1
    [[ ! -d "$DOKKU_ROOT/$2" ]] && echo "App $2 does not exist" && exit 1
    APP="$2"

    cat "$DOKKU_ROOT/$APP/nginx.conf"
  ;;

  nvcc:nginx.conf.d)
    [[ -z $2 ]] && echo "Please specify an app to run the command on" && exit 1
    [[ ! -d "$DOKKU_ROOT/$2" ]] && echo "App $2 does not exist" && exit 1
    APP="$2"

    if [ -d "$DOKKU_ROOT/$APP/nginx.conf.d/" ] && [ "$(ls -A $DOKKU_ROOT/$APP/nginx.conf.d/)" ]; then
      ls -l "$DOKKU_ROOT/$APP/nginx.conf.d/"
    else
      echo "$DOKKU_ROOT/$APP/nginx.conf.d/ does not exist or is empty"
      exit 1
    fi
  ;;

  nvcc:nginx-vhosts-custom-configuration.conf)
    [[ -z $2 ]] && echo "Please specify an app to run the command on" && exit 1
    [[ ! -d "$DOKKU_ROOT/$2" ]] && echo "App $2 does not exist" && exit 1
    APP="$2"

    if [ -f "$DOKKU_ROOT/$APP/nginx.conf.d/nginx-vhosts-custom-configuration.conf" ]; then
      cat "$DOKKU_ROOT/$APP/nginx.conf.d/nginx-vhosts-custom-configuration.conf"
    else
      echo "$DOKKU_ROOT/$APP/nginx.conf.d/nginx-vhosts-custom-configuration.conf does not exist"
      exit 1
    fi
  ;;

  nvcc:port)
    [[ -z $2 ]] && echo "Please specify an app to run the command on" && exit 1
    [[ ! -d "$DOKKU_ROOT/$2" ]] && echo "App $2 does not exist" && exit 1
    APP="$2"

    cat "$DOKKU_ROOT/$APP/PORT"
  ;;

  help)
    cat && cat<<EOF
    nvcc:nginx.conf <app>                               display the current nginx.conf
    nvcc:nginx.conf.d <app>                             display the current nginx.conf.d/ directory contents
    nvcc:nginx-vhosts-custom-configuration.conf <app>   will display the current nginx.conf.d/nginx-vhosts-custom-configuration.conf contents
    nvcc:port <app>                                     will display the current container port
EOF
    ;;

  *)
    exit $DOKKU_NOT_IMPLEMENTED_EXIT
    ;;

esac
